-- INSERT INTO quimicaOrganica(idQO, primerNombre, nombresPosteriores, primerApellido, segundoApellido, edad, nota) VALUES
 -- (1, 'Carlos', 'Antonio', 'Gómez', 'Alvarez', 33, 7.0),
 -- (2, 'Julio', 'Renzo', 'Mendez', 'Gutierrez', 27, 11.0),
 -- (3, 'Lilian', ' ', 'Pérez', 'Sosa', 36, 8.5),
 -- (4, 'Pedro', ' ', 'Carbajal', ' ', 25, 6.2),
 -- (5, 'Elena', ' ', 'Laviano', ' ', 29, 5.0),
 -- (6, 'Mauricio', 'Gonzalo', 'Pereira', 'Alvez', 20, 6.0),
 -- (7, 'Francisco', 'Antonio ', 'Laviano', 'Colman', 39, 5.5)

 -- INSERT INTO fisicoquimica(idFQ, primerNombre, nombresPosteriores, primerApellido, segundoApellido, edad, nota) VALUES
 --  (1, 'Nicolas', ' ', ' Sapriza', 'Brignoni', 24, 12),
 --  (2, 'Yoselin', ' ', 'Prado', ' ', 21, 12.0),
  -- (3, 'Francisco', 'Antonio ', 'Laviano', 'Colman', 39, 7.6),
 --  (4, 'Maria', 'Alejandra Pia', 'Moreira', 'Lapauble ', 43, 9.5),
 --  (5, 'Claudio', ' Ernesto', 'Flores', ' ', 19, 8.0)